name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - run: pip install -r requirements.txt
        
    - run: python -m pytest tests/ --html=report.html --self-contained-html -v
        
    - uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: |
          .
          !.github
